// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_info.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_message_5finfo_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_message_5finfo_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_message_5finfo_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_message_5finfo_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_message_5finfo_2eproto;
namespace message_info {
class MessageInfo;
struct MessageInfoDefaultTypeInternal;
extern MessageInfoDefaultTypeInternal _MessageInfo_default_instance_;
}  // namespace message_info
PROTOBUF_NAMESPACE_OPEN
template<> ::message_info::MessageInfo* Arena::CreateMaybeMessage<::message_info::MessageInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace message_info {

// ===================================================================

class MessageInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:message_info.MessageInfo) */ {
 public:
  inline MessageInfo() : MessageInfo(nullptr) {}
  ~MessageInfo() override;
  explicit PROTOBUF_CONSTEXPR MessageInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MessageInfo(const MessageInfo& from);
  MessageInfo(MessageInfo&& from) noexcept
    : MessageInfo() {
    *this = ::std::move(from);
  }

  inline MessageInfo& operator=(const MessageInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline MessageInfo& operator=(MessageInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MessageInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const MessageInfo* internal_default_instance() {
    return reinterpret_cast<const MessageInfo*>(
               &_MessageInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MessageInfo& a, MessageInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(MessageInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MessageInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MessageInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MessageInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MessageInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MessageInfo& from) {
    MessageInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MessageInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "message_info.MessageInfo";
  }
  protected:
  explicit MessageInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIpFieldNumber = 1,
    kMessageContentFieldNumber = 4,
    kPortFieldNumber = 2,
    kMessageTypeFieldNumber = 3,
  };
  // string ip = 1;
  void clear_ip();
  const std::string& ip() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ip(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ip();
  PROTOBUF_NODISCARD std::string* release_ip();
  void set_allocated_ip(std::string* ip);
  private:
  const std::string& _internal_ip() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ip(const std::string& value);
  std::string* _internal_mutable_ip();
  public:

  // string messageContent = 4;
  void clear_messagecontent();
  const std::string& messagecontent() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_messagecontent(ArgT0&& arg0, ArgT... args);
  std::string* mutable_messagecontent();
  PROTOBUF_NODISCARD std::string* release_messagecontent();
  void set_allocated_messagecontent(std::string* messagecontent);
  private:
  const std::string& _internal_messagecontent() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_messagecontent(const std::string& value);
  std::string* _internal_mutable_messagecontent();
  public:

  // uint32 port = 2;
  void clear_port();
  uint32_t port() const;
  void set_port(uint32_t value);
  private:
  uint32_t _internal_port() const;
  void _internal_set_port(uint32_t value);
  public:

  // int32 messageType = 3;
  void clear_messagetype();
  int32_t messagetype() const;
  void set_messagetype(int32_t value);
  private:
  int32_t _internal_messagetype() const;
  void _internal_set_messagetype(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:message_info.MessageInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ip_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr messagecontent_;
    uint32_t port_;
    int32_t messagetype_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_message_5finfo_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MessageInfo

// string ip = 1;
inline void MessageInfo::clear_ip() {
  _impl_.ip_.ClearToEmpty();
}
inline const std::string& MessageInfo::ip() const {
  // @@protoc_insertion_point(field_get:message_info.MessageInfo.ip)
  return _internal_ip();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void MessageInfo::set_ip(ArgT0&& arg0, ArgT... args) {
 
 _impl_.ip_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:message_info.MessageInfo.ip)
}
inline std::string* MessageInfo::mutable_ip() {
  std::string* _s = _internal_mutable_ip();
  // @@protoc_insertion_point(field_mutable:message_info.MessageInfo.ip)
  return _s;
}
inline const std::string& MessageInfo::_internal_ip() const {
  return _impl_.ip_.Get();
}
inline void MessageInfo::_internal_set_ip(const std::string& value) {
  
  _impl_.ip_.Set(value, GetArenaForAllocation());
}
inline std::string* MessageInfo::_internal_mutable_ip() {
  
  return _impl_.ip_.Mutable(GetArenaForAllocation());
}
inline std::string* MessageInfo::release_ip() {
  // @@protoc_insertion_point(field_release:message_info.MessageInfo.ip)
  return _impl_.ip_.Release();
}
inline void MessageInfo::set_allocated_ip(std::string* ip) {
  if (ip != nullptr) {
    
  } else {
    
  }
  _impl_.ip_.SetAllocated(ip, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.ip_.IsDefault()) {
    _impl_.ip_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:message_info.MessageInfo.ip)
}

// uint32 port = 2;
inline void MessageInfo::clear_port() {
  _impl_.port_ = 0u;
}
inline uint32_t MessageInfo::_internal_port() const {
  return _impl_.port_;
}
inline uint32_t MessageInfo::port() const {
  // @@protoc_insertion_point(field_get:message_info.MessageInfo.port)
  return _internal_port();
}
inline void MessageInfo::_internal_set_port(uint32_t value) {
  
  _impl_.port_ = value;
}
inline void MessageInfo::set_port(uint32_t value) {
  _internal_set_port(value);
  // @@protoc_insertion_point(field_set:message_info.MessageInfo.port)
}

// int32 messageType = 3;
inline void MessageInfo::clear_messagetype() {
  _impl_.messagetype_ = 0;
}
inline int32_t MessageInfo::_internal_messagetype() const {
  return _impl_.messagetype_;
}
inline int32_t MessageInfo::messagetype() const {
  // @@protoc_insertion_point(field_get:message_info.MessageInfo.messageType)
  return _internal_messagetype();
}
inline void MessageInfo::_internal_set_messagetype(int32_t value) {
  
  _impl_.messagetype_ = value;
}
inline void MessageInfo::set_messagetype(int32_t value) {
  _internal_set_messagetype(value);
  // @@protoc_insertion_point(field_set:message_info.MessageInfo.messageType)
}

// string messageContent = 4;
inline void MessageInfo::clear_messagecontent() {
  _impl_.messagecontent_.ClearToEmpty();
}
inline const std::string& MessageInfo::messagecontent() const {
  // @@protoc_insertion_point(field_get:message_info.MessageInfo.messageContent)
  return _internal_messagecontent();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void MessageInfo::set_messagecontent(ArgT0&& arg0, ArgT... args) {
 
 _impl_.messagecontent_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:message_info.MessageInfo.messageContent)
}
inline std::string* MessageInfo::mutable_messagecontent() {
  std::string* _s = _internal_mutable_messagecontent();
  // @@protoc_insertion_point(field_mutable:message_info.MessageInfo.messageContent)
  return _s;
}
inline const std::string& MessageInfo::_internal_messagecontent() const {
  return _impl_.messagecontent_.Get();
}
inline void MessageInfo::_internal_set_messagecontent(const std::string& value) {
  
  _impl_.messagecontent_.Set(value, GetArenaForAllocation());
}
inline std::string* MessageInfo::_internal_mutable_messagecontent() {
  
  return _impl_.messagecontent_.Mutable(GetArenaForAllocation());
}
inline std::string* MessageInfo::release_messagecontent() {
  // @@protoc_insertion_point(field_release:message_info.MessageInfo.messageContent)
  return _impl_.messagecontent_.Release();
}
inline void MessageInfo::set_allocated_messagecontent(std::string* messagecontent) {
  if (messagecontent != nullptr) {
    
  } else {
    
  }
  _impl_.messagecontent_.SetAllocated(messagecontent, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.messagecontent_.IsDefault()) {
    _impl_.messagecontent_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:message_info.MessageInfo.messageContent)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace message_info

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_message_5finfo_2eproto
